"""P3-4 — training-pipeline sanity/regression guard.

Guard the Phase 5 artifacts against silent drift: the gold feature-dataset
shape/schema and the temporal-split row counts. The datasets are gitignored
(large, regenerated by Phase 5), so these tests skip when the files are absent
— a clone cannot run the gate without them, but the guard is active in CI/CD
and on a machine that has run Phase 5.

Expected values (verified 2026-08-15):
  gold_training.parquet  2,770,409 rows x 11 cols (features + step + is_fraud)
  gold_train.parquet     2,217,905 rows x 10 cols
  gold_test.parquet        552,504 rows x 10 cols
  train + test == gold_training (temporal split is a partition of the rows).
"""

import os

import pyarrow.parquet as pq
import pytest

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_DIR, "data")

GOLD_TRAINING_PATH = os.path.join(DATA_DIR, "gold_training.parquet")
GOLD_TRAIN_PATH = os.path.join(DATA_DIR, "gold_train.parquet")
GOLD_TEST_PATH = os.path.join(DATA_DIR, "gold_test.parquet")

EXPECTED_TRAINING_ROWS = 2_770_409
EXPECTED_TRAIN_ROWS = 2_217_905
EXPECTED_TEST_ROWS = 552_504

EXPECTED_GOLD_COLUMNS = [
    "amount",
    "has_balance_orig",
    "balance_delta_orig",
    "error_balance_orig",
    "has_balance_dest",
    "balance_delta_dest",
    "error_balance_dest",
    "is_flagged_fraud",
    "fan_in_dest_count_24h",
    "step",
    "is_fraud",
]


def _read_or_skip(path: str, label: str):
    if not os.path.exists(path):
        pytest.skip(f"{label} dataset missing (Phase 5 not run?) — {path}")
    return pq.read_table(path)


def test_gold_training_shape_and_schema():
    table = _read_or_skip(GOLD_TRAINING_PATH, "gold_training")
    assert table.num_rows == EXPECTED_TRAINING_ROWS
    assert table.num_columns == 11
    assert list(table.schema.names) == EXPECTED_GOLD_COLUMNS


def test_gold_train_split_shape():
    table = _read_or_skip(GOLD_TRAIN_PATH, "gold_train")
    assert table.num_rows == EXPECTED_TRAIN_ROWS
    assert table.num_columns == 10


def test_gold_test_split_shape():
    table = _read_or_skip(GOLD_TEST_PATH, "gold_test")
    assert table.num_rows == EXPECTED_TEST_ROWS
    assert table.num_columns == 10


def test_split_is_a_partition_of_gold_dataset():
    training = _read_or_skip(GOLD_TRAINING_PATH, "gold_training")
    train = _read_or_skip(GOLD_TRAIN_PATH, "gold_train")
    test = _read_or_skip(GOLD_TEST_PATH, "gold_test")
    assert train.num_rows + test.num_rows == training.num_rows
